name: test

on:
  push:
    branches:
      - '**'    
    tags-ignore:
      - '**'
  schedule:
    - cron: "42 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      devnet:
        image: shardlabs/starknet-devnet:0.3.4
        ports:
          - 5050:5050

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: wait for devnet to be up...
        run: ./.bin/devnet.sh

      - name: Test contracts deployment and execute
        run: cd contracts && go test -env devnet -v .

      - name: Test RPC v0.1 with mocks
        run: cd rpcv01 && go test -v .

      - name: Preinstall RPC v0.1 contracts on devnet
        run: cd rpcv01 && go test -timeout 600s -v -env devnet -run TestDeployTransaction . && sleep 5
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "http://localhost:5050/rpc"

      - name: Test Accounts (Caigo) on devnet
        run: go test -timeout 600s -v -env devnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "http://localhost:5050/rpc"

      - name: Test RPC v0.1 on devnet
        run: cd rpcv01 && go test -timeout 600s -v -env devnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "http://localhost:5050/rpc"

      - name: Test sessionkey on devnet
        run: cd plugins/xsessions && ./sessionkey.sh

      - name: Test RPC v0.1 on testnet
        run: cd rpcv01 && go test -timeout 1200s -v -env testnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "https://starknet-goerli.cartridge.gg/"

      - name: Test RPC v0.1 with mainnet
        run: cd rpcv01 && go test -timeout 600s -v -env mainnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "https://starknet.cartridge.gg/"

      - name: Test Gateway with testnet
        run: cd gateway && go test -v -env testnet .

      - name: Test Gateway with devnet
        run: cd gateway && go test -v -env devnet .
