#  https://github.com/crate-ci/typos/blob/master/docs/github-action.md

name: Typos

on: [pull_request]

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: check spelling
        uses: crate-ci/typos@master
